substitutions:
  _REGION: asia-northeast1
  _ARTIFACT_REPOSITORY: learn-fastapi
  _IMAGE_NAME: learn-fastapi-postgresql-app
  _CLOUD_RUN_SERVICE: learn-fastapi-postgresql-app-git
  _RUNTIME_SERVICE_ACCOUNT: cloud-run-fastapi@learn-fastapi-postgresql-app.iam.gserviceaccount.com
  _CLOUD_SQL_INSTANCE: learn-fastapi-postgresql-app:asia-northeast1:learn-fastapi-postgres
  _DATABASE_URL_SECRET: database-url:latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_CLOUD_RUN_SERVICE}
      - --project=$PROJECT_ID
      - --region=${_REGION}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA
      - --service-account=${_RUNTIME_SERVICE_ACCOUNT}
      - --set-secrets=DATABASE_URL=${_DATABASE_URL_SECRET}
      - --set-cloudsql-instances=${_CLOUD_SQL_INSTANCE}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA
